Chapter 3.1: Creating a TODO Contract
YoubetDao/Ethereum-Smart-Contract-Guide pull request #18
Opened 2024-09-08 11:54 UTC by feynman-x

Closes #12

2024-09-11 10:20 UTC, wfnuser requested changes

2024-09-11 10:20 UTC, wfnuser commented on zh/3.1 Creating a TODO Contract.md
> +### About this part
关于本节？

2024-09-11 10:20 UTC, wfnuser commented on zh/3.1 Creating a TODO Contract.md
> +**`SPDX-License-Identifier: MIT`**：这是一种许可证声明. 推荐为合约提供开源许可证（MIT），表明代码可自由使用。**这一行为固定内容, 在实际开发中, 一次没有调整过.**
**这一行为固定内容, 在实际开发中, 一次没有调整过.**
这句话感觉有点奇怪... 或者是不是在作者的实际开发中没有调整过？ 我不太确定 这个协议不能改成 apache 吗？

2024-09-11 10:20 UTC, wfnuser commented on zh/3.1 Creating a TODO Contract.md
> +  **如何设置合适的版本呢?** 如果你使用 hardhat , 参考 `hardhat.config.ts` 中 `solidity.compilers.version` 字段, 保持一致即可.
这里本意是要换行嘛？ 看起来，在 readme 的渲染结果中并没有明显体现出来。

2024-09-11 10:20 UTC, wfnuser commented on zh/3.1 Creating a TODO Contract.md
> +2. **Solidity 版本区别**：研究 Solidity 0.8.x 系列的更新内容，了解为何选择这个版本作为合约编写的起点。参考这篇 [Solidity 0.8.x 更新说明](https://docs.soliditylang.org/en/v0.8.27/080-breaking-changes.html). 这份文档是为了帮助你了解一些基础知识，不需要花很多时间深入学习，先大概浏
结尾增加一个句号好了～

2024-09-13 08:06 UTC, feynman-x commented on zh/3.1 Creating a TODO Contract.md
> +### About this part
对的. 想法是在最开头, 简单的叙述一下本小节的内容.

每个节大概遵行这样的格式:
1. About this part. 
2. xx
3. xxx
4. Summary

2024-09-13 08:10 UTC, feynman-x commented on zh/3.1 Creating a TODO Contract.md
> +**`SPDX-License-Identifier: MIT`**：这是一种许可证声明. 推荐为合约提供开源许可证（MIT），表明代码可自由使用。**这一行为固定内容, 在实际开发中, 一次没有调整过.**
我重新措辞一下, 这里本来想强调说, 使用 MIT 即可, 不需要特别关心

2024-09-13 08:18 UTC, feynman-x commented on zh/3.1 Creating a TODO Contract.md
> +  **如何设置合适的版本呢?** 如果你使用 hardhat , 参考 `hardhat.config.ts` 中 `solidity.compilers.version` 字段, 保持一致即可.
fix

2024-09-13 08:18 UTC, feynman-x commented on zh/3.1 Creating a TODO Contract.md
> +2. **Solidity 版本区别**：研究 Solidity 0.8.x 系列的更新内容，了解为何选择这个版本作为合约编写的起点。参考这篇 [Solidity 0.8.x 更新说明](https://docs.soliditylang.org/en/v0.8.27/080-breaking-changes.html). 这份文档是为了帮助你了解一些基础知识，不需要花很多时间深入学习，先大概浏
fix

2024-09-17 07:55 UTC, wfnuser approved these changes
LGTM.

2024-09-17 07:55 UTC, merged