feat: chapter 4.1
YoubetDao/Ethereum-Smart-Contract-Guide pull request #22
Opened 2024-09-22 12:31 UTC by feynman-x

Closes #19

2024-09-25 12:23 UTC, wfnuser requested changes

2024-09-25 12:23 UTC, wfnuser commented on zh/4.1 Contract Testing.md
> +## 关于本节
感觉是不是每章都放一个大标题会比较好～

2024-09-25 12:23 UTC, wfnuser commented on zh/4.1 Contract Testing.md
> +Hardhat 的测试代码, 统一存放在 test/ 目录下。 例如 test/todo.ts 。
`test` `test/todo.ts`

2024-09-25 12:23 UTC, wfnuser commented on zh/4.1 Contract Testing.md
> +  // 复用初始化代码，避免每次重复部署合约
每个测试用例跑的时候都会独立部署一次合约嘛？ 复用之后避免了吗 这个例子具体复用了什么 我看起来不是很清晰 要不要再解释一下？

2024-09-25 12:23 UTC, wfnuser commented on zh/4.1 Contract Testing.md
> +**测试代码的要素**:
要么要素直接拆成独立的小标题？

2024-09-27 02:21 UTC, feynman-x commented on zh/4.1 Contract Testing.md
> +## 关于本节
确实.  obsidian 会自动渲染一个大标题, 一直没注意到

2024-09-27 02:42 UTC, feynman-x commented on zh/4.1 Contract Testing.md
> +  // 复用初始化代码，避免每次重复部署合约
这里的描述简化了一下, 只强调它是一个函数, 用来合约部署和初始化. 这里暂时不关心部署的细节.

2024-09-27 02:49 UTC, feynman-x commented on zh/4.1 Contract Testing.md
> +**测试代码的要素**:
这小节的标题是 “测试代码结构 & 要素”,  就不单独拆成两个章节了吧

2024-09-27 07:09 UTC, wfnuser commented on zh/4.1 Contract Testing.md
> +**测试代码的要素**:
哈哈哈 我就是问要不要拆 问题不大～

2024-09-27 07:10 UTC, wfnuser approved these changes

2024-09-27 07:10 UTC, merged