feat: chapter about rpc
YoubetDao/Ethereum-Smart-Contract-Guide pull request #33
Opened 2024-10-20 11:24 UTC by feynman-x

Close #31

2024-10-21 03:15 UTC, wfnuser requested changes

2024-10-21 03:15 UTC, wfnuser commented on src/zh/ethereum-development-overview/rpc.md
> +在后面 `Solidity` 开发中，我们与区块链的所有交, 互几乎都依赖于 **`RPC`**。
“所有交互， ”

2024-10-21 03:15 UTC, wfnuser commented on src/zh/ethereum-development-overview/rpc.md
> +你可以把区块链想象成一个远程的服务器（这里的类比只是为了让你有个抽象的概念，并不精确），而 `RPC` 就是发出命令与其进行交互。
“就是发出命令与其进行交互的方式” 是不是更合适

2024-10-27 09:07 UTC, feynman-x commented on src/zh/ethereum-development-overview/rpc.md
> +你可以把区块链想象成一个远程的服务器（这里的类比只是为了让你有个抽象的概念，并不精确），而 `RPC` 就是发出命令与其进行交互。
是的!

2024-10-28 15:48 UTC, merged